/* ============================================
   DownloadReport Component
   Download analysis results as a text report or image
   ============================================ */
'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { useState, useRef, useEffect } from 'react';

export default function DownloadReport({ results }) {
  const [showModal, setShowModal] = useState(false);
  const [reportText, setReportText] = useState('');
  const [copyFeedback, setCopyFeedback] = useState(false);
  const modalRef = useRef(null);

  const generateReport = () => {
    // Build a readable text report
    const { score, breakdown, suggestions, insights } = results || {};

    let report = '';
    report += '═══════════════════════════════════════════\n';
    report += '     RATE MY RESUME — Analysis Report\n';
    report += '═══════════════════════════════════════════\n\n';

    // Overall Score
    report += `📊 OVERALL SCORE: ${score || 0}/100\n\n`;
    report += '── Score Breakdown ──\n';
    if (breakdown) {
      report += `  📋 Formatting:  ${breakdown.formatting || 0}/100\n`;
      report += `  ✍️  Content:     ${breakdown.content || 0}/100\n`;
      report += `  🔧 Skills:      ${breakdown.skills || 0}/100\n`;
      report += `  🔑 Keywords:    ${breakdown.keywords || 0}/100\n`;
    }
    report += '\n';

    // Suggestions
    const cats = ['formatting', 'content', 'skills', 'keywords'];
    const catLabels = { formatting: '📋 FORMATTING', content: '✍️ CONTENT', skills: '🔧 SKILLS', keywords: '🔑 KEYWORDS' };

    report += '═══════════════════════════════════════════\n';
    report += '     IMPROVEMENT SUGGESTIONS\n';
    report += '═══════════════════════════════════════════\n\n';

    cats.forEach((cat) => {
      const items = suggestions?.[cat] || [];
      if (items.length > 0) {
        report += `── ${catLabels[cat]} ──\n`;
        items.forEach((item, i) => {
          report += `  ${i + 1}. [${item.priority?.toUpperCase() || 'LOW'}] ${item.title}\n`;
          report += `     ${item.detail}\n`;
          if (item.example) report += `     Example: ${item.example}\n`;
          report += '\n';
        });
      }
    });

    // AI Insights
    if (insights) {
      report += '═══════════════════════════════════════════\n';
      report += '     AI INSIGHTS\n';
      report += '═══════════════════════════════════════════\n\n';

      if (insights.summary) {
        report += `${insights.summary}\n\n`;
      }
      if (insights.strengths?.length) {
        report += '── Strengths ──\n';
        insights.strengths.forEach((s) => (report += `  ✅ ${s}\n`));
        report += '\n';
      }
      if (insights.weaknesses?.length) {
        report += '── Areas to Improve ──\n';
        insights.weaknesses.forEach((w) => (report += `  ⚠️ ${w}\n`));
        report += '\n';
      }
      if (insights.skillGaps?.length) {
        report += '── Skill Gaps ──\n';
        report += `  ${insights.skillGaps.join(', ')}\n\n`;
      }
      if (insights.actionItems?.length) {
        report += '── Top Action Items ──\n';
        insights.actionItems.forEach((a, i) => (report += `  ${i + 1}. ${a}\n`));
        report += '\n';
      }
    }

    report += '═══════════════════════════════════════════\n';
    report += '  Generated by RateMyResume\n';
    report += `  Date: ${new Date().toLocaleDateString()}\n`;
    report += '═══════════════════════════════════════════\n';

    return report;
  };

  const handleViewAnalysis = () => {
    const report = generateReport();
    setReportText(report);
    setShowModal(true);
  };

  const handleDownload = () => {
    const report = generateReport();

    // Download as text file
    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    // Extract filename without extension for cleaner download name
    const fileName = results?.fileName?.split('.')[0] || 'resume';
    a.download = `resumeanalysis-${fileName}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(reportText).then(() => {
      setCopyFeedback(true);
      setTimeout(() => setCopyFeedback(false), 2000);
    });
  };

  const handleBackdropClick = (e) => {
    if (modalRef.current && e.target === modalRef.current) {
      setShowModal(false);
    }
  };

  return (
    <>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.6 }}
        className="flex flex-col sm:flex-row items-center gap-3"
      >
        {/* View analysis in modal */}
        <button
          onClick={handleViewAnalysis}
          className="btn-outline flex items-center justify-center w-11 h-11 p-0 transition-all hover:scale-105"
          id="view-analysis-btn"
          title="View analysis report"
        >
          <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
        </button>

        {/* Download/Analysis button - PROMINENT */}
        <button
          onClick={handleDownload}
          className="btn-primary flex items-center gap-2 px-8 py-3 text-lg font-semibold rounded-lg shadow-lg hover:shadow-xl transition-all hover:scale-105 bg-gradient-to-r from-primary-500 to-accent-violet hover:from-primary-600 hover:to-accent-violet/90"
          id="analysis-btn"
          title="Download analysis as text file"
        >
          <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 17v2a2 2 0 002 2h12a2 2 0 002-2v-2" />
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 3v12m0 0l4-4m-4 4L8 11" />
          </svg>
          Analysis
        </button>
      </motion.div>

      {/* Modal Popup */}
      <AnimatePresence>
        {showModal && (
          <motion.div
            ref={modalRef}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={handleBackdropClick}
            className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="bg-surface-900 rounded-lg shadow-2xl w-full max-w-2xl max-h-[80vh] flex flex-col"
            >
              {/* Modal Header */}
              <div className="flex items-center justify-between p-4 border-b border-surface-800">
                <h3 className="text-lg font-semibold text-white flex items-center gap-2">
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Analysis Report
                </h3>
                <div className="flex items-center gap-2">
                  {/* Copy Button */}
                  <button
                    onClick={handleCopyToClipboard}
                    className="p-2 hover:bg-surface-800 rounded transition-colors relative group"
                    title="Copy to clipboard"
                  >
                    <svg className="w-5 h-5 text-surface-300 group-hover:text-white transition-colors" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                    </svg>
                    {copyFeedback && (
                      <span className="absolute -top-8 left-1/2 transform -translate-x-1/2 bg-green-600 text-white text-xs px-2 py-1 rounded whitespace-nowrap">
                        Copied!
                      </span>
                    )}
                  </button>
                  {/* Close Button */}
                  <button
                    onClick={() => setShowModal(false)}
                    className="p-2 hover:bg-surface-800 rounded transition-colors"
                    title="Close"
                  >
                    <svg className="w-5 h-5 text-surface-300 hover:text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </button>
                </div>
              </div>

              {/* Modal Content */}
              <div className="flex-1 overflow-y-auto p-4">
                <pre className="text-xs text-surface-300 font-mono whitespace-pre-wrap break-words">
                  {reportText}
                </pre>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
